In [ ]:
import os


print(os.listdir())


['dws_1', 'dws_11', 'dws_2', 'jog_16', 'jog_9', 'sit_13', 'sit_5', 'std_14', 'std_6', 'ups_12', 'ups_3', 'ups_4', 'wlk_15', 'wlk_7', 'wlk_8']


In [ ]:
import os

base_path = r"C:\Users\Hp\Downloads\archive (1)\A_DeviceMotion_data\A_DeviceMotion_data"  
print(os.listdir(base_path))


['dws_1', 'dws_11', 'dws_2', 'jog_16', 'jog_9', 'sit_13', 'sit_5', 'std_14', 'std_6', 'ups_12', 'ups_3', 'ups_4', 'wlk_15', 'wlk_7', 'wlk_8']


In [ ]:
import pandas as pd
import os


base_path = r"C:\Users\Hp\Downloads\archive (1)\A_DeviceMotion_data\A_DeviceMotion_data"

folders = ['dws_1', 'dws_11', 'dws_2', 'jog_16', 'jog_9', 'sit_13', 'sit_5', 
           'std_14', 'std_6', 'ups_12', 'ups_3', 'ups_4', 'wlk_15', 'wlk_7', 'wlk_8']

all_data = []

for folder in folders:
    folder_path = os.path.join(base_path, folder)
    
    for file in os.listdir(folder_path):
        if file.endswith(".csv") or file.endswith(".txt"):
            file_path = os.path.join(folder_path, file)
            df = pd.read_csv(file_path, header=None)
            df['label'] = folder[:3]  
            all_data.append(df)

df_all = pd.concat(all_data, ignore_index=True)

print(df_all.head())
print(df_all['label'].value_counts())


     0                   1                    2                   3  \
0  NaN       attitude.roll       attitude.pitch        attitude.yaw   
1  0.0            1.528132            -0.733896            0.696372   
2  1.0            1.527992            -0.716987            0.677762   
3  2.0            1.527765  -0.7069989999999999  0.6709510000000001   
4  3.0  1.5167680000000001            -0.704678  0.6757350000000001   

                    4          5                      6                     7  \
0           gravity.x  gravity.y              gravity.z        rotationRate.x   
1            0.741895   0.669768  -0.031672000000000006              0.316738   
2            0.753099   0.657116              -0.032255              0.842032   
3  0.7596109999999999   0.649555              -0.032707  -0.13814300000000002   
4            0.760709   0.647788  -0.041139999999999996             -0.025005   

                8                   9                   10  \
0  rotationRate.y      r

In [9]:
import pandas as pd
import os

base_path = r"C:\Users\Hp\Downloads\archive (1)\A_DeviceMotion_data\A_DeviceMotion_data"

folders = ['dws_1', 'dws_11', 'dws_2', 'jog_16', 'jog_9', 'sit_13', 'sit_5', 
           'std_14', 'std_6', 'ups_12', 'ups_3', 'ups_4', 'wlk_15', 'wlk_7', 'wlk_8']

columns = [
    "time", "attitude.roll", "attitude.pitch", "attitude.yaw",
    "gravity.x", "gravity.y", "gravity.z",
    "rotationRate.x", "rotationRate.y", "rotationRate.z",
    "userAcceleration.x", "userAcceleration.y", "userAcceleration.z"
]

all_data = []

for folder in folders:
    folder_path = os.path.join(base_path, folder)
    
    for file in os.listdir(folder_path):
        if file.endswith(".csv") or file.endswith(".txt"):
            file_path = os.path.join(folder_path, file)
            df = pd.read_csv(file_path, skiprows=1, header=None, names=columns)
            df['label'] = folder[:3]
            all_data.append(df)

df_all = pd.concat(all_data, ignore_index=True)

print(df_all.head())
print(df_all['label'].value_counts())


   time  attitude.roll  attitude.pitch  attitude.yaw  gravity.x  gravity.y  \
0     0       1.528132       -0.733896      0.696372   0.741895   0.669768   
1     1       1.527992       -0.716987      0.677762   0.753099   0.657116   
2     2       1.527765       -0.706999      0.670951   0.759611   0.649555   
3     3       1.516768       -0.704678      0.675735   0.760709   0.647788   
4     4       1.493941       -0.703918      0.672994   0.760062   0.647210   

   gravity.z  rotationRate.x  rotationRate.y  rotationRate.z  \
0  -0.031672        0.316738        0.778180        1.082764   
1  -0.032255        0.842032        0.424446        0.643574   
2  -0.032707       -0.138143       -0.040741        0.343563   
3  -0.041140       -0.025005       -1.048717        0.035860   
4  -0.058530        0.114253       -0.912890        0.047341   

   userAcceleration.x  userAcceleration.y  userAcceleration.z label  
0            0.294894           -0.184493            0.377542   dws  
1     

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix


le = LabelEncoder()
df_all['label_encoded'] = le.fit_transform(df_all['label'])


sample_df = df_all.sample(frac=0.1, random_state=42)

X = sample_df.drop(columns=['label', 'label_encoded', 'time'])
y = sample_df['label_encoded']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)


model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)


model.fit(X_train, y_train)


y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))


Confusion Matrix:
[[1516  160    2    7  264  656]
 [ 127 2151    2    0   65  330]
 [   0    0 6721    0    6    3]
 [  19    0    0 6063   36   12]
 [ 205   93    2   21 2115  769]
 [ 140  119    0   13  228 6413]]

Classification Report:
              precision    recall  f1-score   support

         dws       0.76      0.58      0.66      2605
         jog       0.85      0.80      0.83      2675
         sit       1.00      1.00      1.00      6730
         std       0.99      0.99      0.99      6130
         ups       0.78      0.66      0.71      3205
         wlk       0.78      0.93      0.85      6913

    accuracy                           0.88     28258
   macro avg       0.86      0.83      0.84     28258
weighted avg       0.88      0.88      0.88     28258



In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df_all['label_encoded'] = le.fit_transform(df_all['label'])


sample_df = df_all.sample(frac=0.1, random_state=42)

X = sample_df.drop(columns=['label', 'label_encoded', 'time'])
y = sample_df['label_encoded']


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


pca = PCA(n_components=0.95, random_state=42)
X_pca = pca.fit_transform(X_scaled)

print(f"عدد الميزات بعد PCA: {X_pca.shape[1]}")  


X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y, test_size=0.2, random_state=42, stratify=y)


model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))


عدد الميزات بعد PCA: 10
Confusion Matrix:
[[1314  165    0   32  301  793]
 [ 113 2139    0    0   64  359]
 [   0    0 6717    0    8    5]
 [  16    0    0 6063   39   12]
 [ 207  117    4   57 1940  880]
 [ 144  136    0   22  242 6369]]

Classification Report:
              precision    recall  f1-score   support

         dws       0.73      0.50      0.60      2605
         jog       0.84      0.80      0.82      2675
         sit       1.00      1.00      1.00      6730
         std       0.98      0.99      0.99      6130
         ups       0.75      0.61      0.67      3205
         wlk       0.76      0.92      0.83      6913

    accuracy                           0.87     28258
   macro avg       0.84      0.80      0.82     28258
weighted avg       0.87      0.87      0.86     28258



In [13]:
pip install xgboost


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\Hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df_all['label_encoded'] = le.fit_transform(df_all['label'])


sample_df = df_all.sample(frac=0.1, random_state=42)

X = sample_df.drop(columns=['label', 'label_encoded', 'time'])
y = sample_df['label_encoded']


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


pca = PCA(n_components=0.95, random_state=42)
X_pca = pca.fit_transform(X_scaled)

print(f"عدد الميزات بعد PCA: {X_pca.shape[1]}")


X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y, test_size=0.2, random_state=42, stratify=y)


dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)


params = {
    'objective': 'multi:softmax',
    'num_class': len(le.classes_),
    'eval_metric': 'mlogloss',
    'seed': 42,
    'verbosity': 1,
}


num_rounds = 100
model = xgb.train(params, dtrain, num_boost_round=num_rounds)


y_pred = model.predict(dtest)


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))


عدد الميزات بعد PCA: 10
Confusion Matrix:
[[1174  169    1   38  377  846]
 [ 130 2007    0    0   77  461]
 [   0    0 6721    0    5    4]
 [  19    0    0 6070   29   12]
 [ 244  110    1   64 1837  949]
 [ 292  188    0   25  394 6014]]

Classification Report:
              precision    recall  f1-score   support

         dws       0.63      0.45      0.53      2605
         jog       0.81      0.75      0.78      2675
         sit       1.00      1.00      1.00      6730
         std       0.98      0.99      0.98      6130
         ups       0.68      0.57      0.62      3205
         wlk       0.73      0.87      0.79      6913

    accuracy                           0.84     28258
   macro avg       0.80      0.77      0.78     28258
weighted avg       0.84      0.84      0.84     28258



In [ ]:
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df_all['label_encoded'] = le.fit_transform(df_all['label'])

sample_df = df_all.sample(frac=0.1, random_state=42)

X = sample_df.drop(columns=['label', 'label_encoded', 'time'])
y = sample_df['label_encoded']


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y)


dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

params = {
    'objective': 'multi:softmax',
    'num_class': len(le.classes_),
    'eval_metric': 'mlogloss',
    'seed': 42,
    'verbosity': 1,
}


num_rounds = 100
model = xgb.train(params, dtrain, num_boost_round=num_rounds)


y_pred = model.predict(dtest)


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))


Confusion Matrix:
[[1428  150    2   11  322  692]
 [ 132 2114    2    0   76  351]
 [   1    1 6722    0    5    1]
 [  13    0    0 6073   33   11]
 [ 251   99    0   29 1990  836]
 [ 251  151    0   17  356 6138]]

Classification Report:
              precision    recall  f1-score   support

         dws       0.69      0.55      0.61      2605
         jog       0.84      0.79      0.81      2675
         sit       1.00      1.00      1.00      6730
         std       0.99      0.99      0.99      6130
         ups       0.72      0.62      0.66      3205
         wlk       0.76      0.89      0.82      6913

    accuracy                           0.87     28258
   macro avg       0.83      0.81      0.82     28258
weighted avg       0.86      0.87      0.86     28258



In [ ]:
import xgboost as xgb
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
import numpy as np


le = LabelEncoder()
df_all['label_encoded'] = le.fit_transform(df_all['label'])

sample_df = df_all.sample(frac=0.1, random_state=42)

X = sample_df.drop(columns=['label', 'label_encoded', 'time'])
y = sample_df['label_encoded']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y)

model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(le.classes_), use_label_encoder=False, eval_metric='mlogloss', verbosity=1, seed=42)


param_dist = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.3, 0.5]
}

random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=20,
    scoring='accuracy',
    cv=3, 
    verbose=2,
    random_state=42,
    n_jobs=-1
)


random_search.fit(X_train, y_train)


print("أفضل معلمات بعد البحث:")
print(random_search.best_params_)


y_pred = random_search.best_estimator_.predict(X_test)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))


Fitting 3 folds for each of 20 candidates, totalling 60 fits


C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\xgboost\training.py:183: UserWarning: [23:42:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


أفضل معلمات بعد البحث:
{'subsample': 0.8, 'n_estimators': 150, 'max_depth': 9, 'learning_rate': 0.2, 'gamma': 0, 'colsample_bytree': 0.8}

Confusion Matrix:
[[1653  127    2    8  303  512]
 [ 115 2244    1    0   80  235]
 [   0    0 6720    0    6    4]
 [  19    0    0 6074   27   10]
 [ 241   99    0   25 2237  603]
 [ 193  109    0   15  284 6312]]

Classification Report:
              precision    recall  f1-score   support

         dws       0.74      0.63      0.69      2605
         jog       0.87      0.84      0.85      2675
         sit       1.00      1.00      1.00      6730
         std       0.99      0.99      0.99      6130
         ups       0.76      0.70      0.73      3205
         wlk       0.82      0.91      0.87      6913

    accuracy                           0.89     28258
   macro avg       0.87      0.85      0.85     28258
weighted avg       0.89      0.89      0.89     28258



In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split


le = LabelEncoder()
df_all['label_encoded'] = le.fit_transform(df_all['label'])


X = df_all.drop(columns=['label', 'label_encoded', 'time']).values
y = df_all['label_encoded'].values


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


sequence_length = 20

def create_sequences(X, y, seq_length):
    X_seq, y_seq = [], []
    for i in range(len(X) - seq_length):
        X_seq.append(X[i:i+seq_length])
        y_seq.append(y[i+seq_length])
    return np.array(X_seq), np.array(y_seq)

X_seq, y_seq = create_sequences(X_scaled, y, sequence_length)


X_train, X_test, y_train, y_test = train_test_split(X_seq, y_seq, test_size=0.2, random_state=42, stratify=y_seq)

y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)


model = Sequential()
model.add(LSTM(64, input_shape=(sequence_length, X.shape[1]), return_sequences=False))
model.add(Dropout(0.3))
model.add(Dense(len(le.classes_), activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


model.fit(X_train, y_train_cat, epochs=10, batch_size=64, validation_split=0.1)


loss, accuracy = model.evaluate(X_test, y_test_cat)
print(f"Test accuracy: {accuracy:.4f}")


C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 159s 10ms/step - accuracy: 0.9312 - loss: 0.2142 - val_accuracy: 0.9792 - val_loss: 0.0722
Epoch 2/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 156s 10ms/step - accuracy: 0.9802 - loss: 0.0706 - val_accuracy: 0.9842 - val_loss: 0.0534
Epoch 3/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 155s 10ms/step - accuracy: 0.9840 - loss: 0.0544 - val_accuracy: 0.9863 - val_loss: 0.0447
Epoch 4/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 202s 10ms/step - accuracy: 0.9863 - loss: 0.0455 - val_accuracy: 0.9879 - val_loss: 0.0388
Epoch 5/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 154s 10ms/step - accuracy: 0.9882 - loss: 0.0393 - val_accuracy: 0.9887 - val_loss: 0.0360
Epoch 6/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 155s 10ms/step - accuracy: 0.9891 - loss: 0.0354 - val_accuracy: 0.9907 - val_loss: 0.0294
Epoch 7/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 154s 10ms/step - accuracy: 0.9903 - loss: 0.0313 - val_accuracy: 0.9901 - val_loss: 0.0314
Epoch 8/10
15895/15895 ━━━━━━━━━━━━━━━━━━━━ 157s 10ms/s

In [21]:
model.save("final_model.keras")
